from __future__ import annotations

JEREMY_BIG_SCREEN_SETTINGS = (5200, 1300, 20)
JEREMY_LAPTOP_SETTINGS = (1400, 800, 10)
SCREEN_WIDTH, SCREEN_HEIGHT, TILE_SIZE = JEREMY_LAPTOP_SETTINGS
MIN_TILE_SIZE = 1

# Settings
STARTING_ANIMAL_SPAWNING_CHANCE = .01
STARTING_PLANT_SPAWNING_CHANCE = .5