from pygame.math import lerp
from random import random

# Organisms
ENERGY_TO_HEALTH_RATIO: float = .5
HEALTH_TO_ENERGY_RATIO: float = 1 / ENERGY_TO_HEALTH_RATIO
ORGANISM_BASE_ATTACK_POWER: float = 0
ORGANISM_BASE_ENERGY_MAINTANCE: float = 1

# Animals
ANIMAL_BASE_ATTACK_POWER: float = 8

# Plants
PLANT_MAX_HEALTH: float = 200
PLANT_MAX_ENERGY: float = 100
PLANT_STARTING_HEALTH: float = lambda: PLANT_MAX_HEALTH * lerp(.8, 1, random())
PLANT_STARTING_ENERGY: float = lambda: PLANT_MAX_ENERGY * lerp(.8, 1, random())
PLANT_NUTRITION_FACTOR: float = .8
PLANT_REPRODUCTION_CHANCE_FACTOR: float = .01
PLANT_BASE_ATTACK_POWER: float = 0
PLANT_REPRODUCTION_ENERGY_COST_FACTOR: float = .25
PLANT_OFFSPRING_HEALTH_FACTOR: float = .25
PLANT_MIN_REPRODUCTION_HEALTH: float = .1
PLANT_MIN_REPRODUCTION_ENERGY: float = .3
PLANT_PHOTOSYNTHESIS_ENERGY_MULTIPLIER: float = 3
PLANT_COAST_ENERGY_MULTIPLIER: float = 1